# Generated by Django 5.1.1 on 2024-10-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HWFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hw_title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='hw_files/')),
                ('status', models.CharField(choices=[('checked', 'Checked'), ('unchecked', 'Unchecked'), ('okay', 'Okay')], default='unchecked', max_length=10)),
            ],
        ),
    ]
